package ffmpeg

var GlobalOptions = []string{
	`-y`,
	`-n`,
	`-recast_media`,
	`-filter_threads`,
	`-filter_buffered_frames`,
	`-stats`,
	`-stats_period`,
	`-print_graphs`,
	`-print_graphs_file`,
	`-print_graphs_format`,
	`-progress`,
	`-debug_ts`,
	`-benchmark`,
	`-benchmark_all`,
	`-timelimit`,
	`-dump`,
	`-hex`,
	`-vsync`,
	`-filter_complex`,
	`-filter_complex_threads`,
	`-lavfi filtergraph`,
	`-sdp_file`,
	`-abort_on`,
	`-max_error_rate`,
	`-xerror`,
	`-auto_conversion_filters`,
}
